FROM mcr.microsoft.com/dotnet/sdk:6.0

WORKDIR /app

RUN dotnet tool install --global dotnet-ef --version 6.0.21
ENV PATH="$PATH:/root/.dotnet/tools"

COPY . .
RUN dotnet restore

ENTRYPOINT ["dotnet", "ef"]
